---
name: "CI/CD"

"on":
  push: {}

jobs:
  yamllint-job:
    runs-on: "ubuntu-24.04"
    container:
      image: "pipelinecomponents/yamllint:0.35.9"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4.2.2"
      - name: "Execute yamllint"
        run: "yamllint ."

  markdownlint-job:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/igorshubovych/markdownlint-cli:v0.45.0"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4.2.2"
      - name: "Execute markdownlint"
        run: "markdownlint ."
...
